using Microsoft.EntityFrameworkCore;
using Northgate.Api.Data.Entities;

namespace Northgate.Api.Data;

// db/001_schema.sql is the source of truth; this model is mapped to match it.
//
// Table names, column names and types, keys, FKs, precision and indexes are
// declared as data annotations on the entity classes themselves. What remains
// here is only what data annotations cannot express -- there is no attribute
// form for any of it:
//
//   * PostgreSQL extensions (pg_trgm)
//   * check constraints
//   * database-side default values (now(), minor_unit = 2)
//   * GENERATED ALWAYS AS IDENTITY (the [DatabaseGenerated] attribute yields
//     GENERATED BY DEFAULT, which is a weaker guarantee)
//   * constraint *names* for primary and foreign keys -- without these EF would
//     emit PK_customers / FK_customers_countries_country_code instead of the
//     Postgres-idiomatic customers_pkey / customers_country_code_fkey
//   * ON DELETE behaviour
//   * the GIN trigram index, which needs an index method and operator class
public sealed class NorthgateDbContext : DbContext
{
    public NorthgateDbContext(DbContextOptions<NorthgateDbContext> options)
        : base(options)
    {
    }

    public DbSet<Country> Countries => Set<Country>();
    public DbSet<Currency> Currencies => Set<Currency>();
    public DbSet<Customer> Customers => Set<Customer>();
    public DbSet<FxRate> FxRates => Set<FxRate>();
    public DbSet<Transaction> Transactions => Set<Transaction>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasPostgresExtension("pg_trgm");

        modelBuilder.Entity<Country>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("countries_pkey");
            entity.ToTable(t => t.HasCheckConstraint("countries_code_upper", "code = upper(code)"));
        });

        modelBuilder.Entity<Currency>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("currencies_pkey");
            entity.ToTable(t =>
            {
                t.HasCheckConstraint("currencies_code_upper", "code = upper(code)");
                t.HasCheckConstraint("currencies_minor_unit_range", "minor_unit BETWEEN 0 AND 4");
            });

            entity.Property(e => e.MinorUnit).HasDefaultValue((short)2);
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("customers_pkey");
            entity.ToTable(t =>
            {
                t.HasCheckConstraint("customers_full_name_not_blank", "btrim(full_name) <> ''");
                t.HasCheckConstraint("customers_document_not_blank", "btrim(document_number) <> ''");
            });

            entity.Property(e => e.Id).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("now()");

            entity.HasOne(e => e.Country)
                .WithMany(c => c.Customers)
                .HasForeignKey(e => e.CountryCode)
                .HasConstraintName("customers_country_code_fkey")
                .OnDelete(DeleteBehavior.NoAction);

            // GIN + trigrams is what makes the leading-wildcard ILIKE indexable.
            entity.HasIndex(e => e.FullName)
                .HasDatabaseName("customers_full_name_trgm")
                .HasMethod("gin")
                .HasOperators("gin_trgm_ops");
        });

        modelBuilder.Entity<FxRate>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("fx_rates_pkey");
            entity.ToTable(t =>
            {
                t.HasCheckConstraint("fx_rates_rate_positive", "rate > 0");
                t.HasCheckConstraint("fx_rates_distinct_pair", "base_code <> quote_code");
            });

            entity.Property(e => e.Id).UseIdentityAlwaysColumn();

            entity.HasOne(e => e.BaseCurrency)
                .WithMany()
                .HasForeignKey(e => e.BaseCode)
                .HasConstraintName("fx_rates_base_code_fkey")
                .OnDelete(DeleteBehavior.NoAction);

            entity.HasOne(e => e.QuoteCurrency)
                .WithMany()
                .HasForeignKey(e => e.QuoteCode)
                .HasConstraintName("fx_rates_quote_code_fkey")
                .OnDelete(DeleteBehavior.NoAction);
        });

        modelBuilder.Entity<Transaction>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("transactions_pkey");
            entity.ToTable(t => t.HasCheckConstraint("transactions_amount_nonzero", "amount <> 0"));

            entity.Property(e => e.Id).UseIdentityAlwaysColumn();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("now()");

            entity.HasOne(e => e.Customer)
                .WithMany(c => c.Transactions)
                .HasForeignKey(e => e.CustomerId)
                .HasConstraintName("transactions_customer_id_fkey")
                .OnDelete(DeleteBehavior.NoAction);

            entity.HasOne(e => e.Currency)
                .WithMany(c => c.Transactions)
                .HasForeignKey(e => e.CurrencyCode)
                .HasConstraintName("transactions_currency_code_fkey")
                .OnDelete(DeleteBehavior.NoAction);

            entity.HasOne(e => e.FxRate)
                .WithMany()
                .HasForeignKey(e => e.FxRateId)
                .HasConstraintName("transactions_fx_rate_id_fkey")
                .OnDelete(DeleteBehavior.NoAction);
        });
    }
}
